# Generated by Django 5.0.2 on 2025-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDBApp', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
