# Generated by Django 5.1.7 on 2025-05-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDBApp', '0007_favorite_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
