# Generated by Django 5.2 on 2025-04-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDBApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('director', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('genre', models.ManyToManyField(related_name='movies', to='MovieDBApp.genre')),
            ],
        ),
    ]
