# Generated by Django 5.1.7 on 2025-05-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDBApp', '0006_remove_movie_genre_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
